### ISSUE TITLE
Awtrix App on Android - Missing pixel in lower right corner of clock display rendering

### ISSUE THREAD

**Issue by mleiber** [Blueforcer/awtrix3#517]
Looks like the clock display rendering in the mobile phone app (on Android at least) is missing a pixel.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: 0.96
  - App version:  0.0.29 (17.03.2024)
  - Google Pixel 7 Pro running Android version 14, Build AP1A.240305.019.A1 

Send this to the display:

````
service: mqtt.publish
data:
  topic: awtrix_wohnhalle/notify
  payload:  "{ background: '#ff0000', text: 'abc' }"
````

The expectation would be a red square underneath the text. Instead you get a square with the right/bottom-most pixel missing.

See screenshot:

![WhatsApp Bild 2024-03-24 um 09 32 00_8d87521e](https://github.com/Blueforcer/awtrix3/assets/52375201/3df619ac-cfa7-4a88-b110-7655d1a214f9)

At the same time on the 'real thing', (the physical Ulanzi clock display) the red square is complete including the missing pixel.
