### ISSUE TITLE
[BUG] Scrolling longer text (like NINA warnings) "stutters" enormously, making warnings hard to read

### ISSUE THREAD

**Issue by Moonbase59** [Blueforcer/awtrix3#674]
# Bug report

## Describe the bug

Scrolling longer texts—like NINA Warnings—"stutters" a lot, making warnings uncomfortable to read. I _think_ this went smoother on v0.96, but ain't entirely sure. The enclosed GIF recording from Live View doesn't show the stuttering very well, it is much worse on the display.

![awtrix](https://github.com/user-attachments/assets/d5ca484c-ae8a-47c6-9ca7-f71ebe41da09)

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: v0.98

## To Reproduce

I use the following (from Home Assistant/MQTT) to display a NINA warning:

```yaml
data:
  qos: 2
  retain: false
  payload: |-
    {
      "text": "{{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1", "headline") | replace("<br/>", " ") | striptags }}: {{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1", "description") | replace("<br/>", " ") | striptags }}",
      "icon": "9335",
      "pushIcon": 2,
      "repeat": 1
    }
  topic: awtrix1/custom/nina
action: mqtt.publish
```

## Expected behavior

Don't know if that's actually possible, but smoother text scrolling for long texts would be superb, especially when a device is used to display warnings.

## Screenshots

(See GIF above)

## Logs

—

## Additional context

—

**Comment by distanzcheck** [comment]
Hello, which add-on / integration is this?

**Comment by distanzcheck** [comment]
OT: Yes, I also have Nina running with me. Would you make your automations available, display on Ulanzi clock ?  Dirk

**Comment by Blueforcer** [comment]
@Moonbase59 how long is your text?
I've tested it with a 380 character string, and it's a very smooth scrolling. Do you use the scroll speed option?

**Comment by Moonbase59** [comment]
@Blueforcer Counting above (real) text, I get 340 chars. NINA descriptions can be longer, though. I left scroll speed at default (i.e., never change it). Typical NINA headline+description seem to be around 300–500 chars (after striptags).

Experimenting a little more, I can see the same effect (stutter, hickups) when globally activating the "snow" overlay. Indeed looks a bit like something else hitting in (MQTT app updates?). WiFi reception is quite ok (-55 dBm; about 2 metres from the router), and WiFi total 2.4GHz bandwith usage ~11% (as measured by Fritz!Box router). So nothing unusual here.

Then again, I only use one built-in app (Time), and 7 others in the standard loop, plus NINA and notifications when needed.

`awtrix1/api/loop` currently shows (no NINA warning currently):
```json
{
  "Time": 0,
  "weather": 1,
  "weather_night": 2,
  "weather_fridge": 3,
  "weather_humidity": 4,
  "weather_wind": 5,
  "weather_uv": 6,
  "effect": 7
}
```

My `dev.json` is:
```json
{
  "hostname": "awtrix1",
  "matrix": 0,
  "temp_offset": -10.7,
  "temp_dec_places": 1,
  "hum_offset": 8,
  "min_brightnexx": 1,
  "max_brightness": 100,
  "new_year": true
}
```

My `awtrix1/api/stats`, if it helps:
```json
{
  "bat": 100,
  "bat_raw": 666,
  "type": 0,
  "lux": 0,
  "ldr_raw": 201,
  "ram": 117564,
  "bri": 2,
  "temp": 20.7,
  "hum": 38,
  "uptime": 196768,
  "wifi_signal": -55,
  "messages": 206395,
  "version": "0.98",
  "indicator1": false,
  "indicator2": false,
  "indicator3": false,
  "app": "weather_night",
  "uid": "awtrix_4276d0",
  "matrix": true,
  "ip_address": "192.168.170.102"
}
```

Anything else you want me to check?

---

@distanzcheck Yeah, sure, here goes. You'll have to adapt MQTT topics and entity names, and you need icon \#9335.

NINA Automation (shows/notifies only warning \#1):
```yaml
alias: NINA-Warnung Krumbach
description: ""
triggers:
  - entity_id: binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1
            state: "on"
        sequence:
          - data:
              qos: 2
              retain: false
              payload: |-
                {
                  "text": "{{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1", "headline") | replace("<br/>", " ") | striptags }}: {{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1", "description") | replace("<br/>", " ") | striptags }}",
                  "icon": "9335",
                  "pushIcon": 2,
                  "repeat": 1
                }
              topic: awtrix1/custom/nina
            action: mqtt.publish
          - data:
              qos: 2
              retain: false
              payload: |-
                {
                  "color": [255,0,0]
                }
              topic: awtrix1/indicator1
            action: mqtt.publish
          - action: notify.notify
            metadata: {}
            data:
              data:
                priority: high
              title: >-
                NINA-Warnung ({{
                state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
                "severity") }})
              message: >-
                {{
                state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
                "headline") }}: {{
                state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
                "description") }}


                {{
                state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
                "recommended_actions") }}
      - conditions:
          - condition: state
            entity_id: binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1
            state: "off"
        sequence:
          - data:
              qos: 2
              retain: false
              topic: awtrix1/custom/nina
            action: mqtt.publish
          - data:
              qos: 2
              retain: false
              topic: awtrix1/indicator1
            action: mqtt.publish
          - action: notify.notify
            metadata: {}
            data:
              data:
                priority: high
              title: NINA-Warnung aufgehoben
              message: NINA-Warnung wurde aufgehoben.
```

Code for a simple dashboard Markdown card:
```yaml
type: markdown
content: >
  {{
  as_timestamp(state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "sent")) | timestamp_custom('%a %d.%m.%Y %H:%M') }}

  {{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "sender") }}


  {{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "severity") }}

  {{
  as_timestamp(state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "start")) | timestamp_custom('%a %d.%m.%Y %H:%M') }} – {{
  as_timestamp(state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "expires")) | timestamp_custom('%a %d.%m.%Y %H:%M') }}


  ### {{
  state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "headline") }}


  **{{
  state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "description") }}**



  {{ state_attr("binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1",
  "recommended_actions") }}
visibility:
  - condition: state
    entity: binary_sensor.warning_krumbach_schwaben_st_gunzburg_bayern_1
    state: "on"
title: NINA-Warnung
```
