### ISSUE TITLE
[BUG] Changing moodlight color and brightness independently

### ISSUE THREAD

**Issue by palves** [Blueforcer/awtrix3#679]
# Bug report

## Describe the bug

I exposed the mood light to Home Assistant as an MQTT light in my configuration.yaml, like so:

```
mqtt:
  light:
    - name: "Awtrix Office Mood Light"
      command_topic: "awtrix/office/moodlight"
      payload_on: ''
      payload_off: ''
      brightness_command_topic: "awtrix/office/moodlight"
      brightness_command_template: '{"brightness":{{ value | int }}}'
      brightness_scale: 255
      rgb_command_topic: "awtrix/office/moodlight"
      rgb_command_template: '{"color":[{{ red | int }},{{ green | int }},{{ blue | int }}]}'
      qos: 1
      retain: true
      on_command_type: brightness
      availability_topic: "awtrix/office/3c8a1f59215c/avty_t"
```

That works OK-ish, and is useful to test colors on the device, or just for fun, as Home Assistant's light entity lets you control the brightness and the color of the "light" using nice color picker and brightness slider UI widgets.

There is just one nagging thing.  Home assistant controls brightness and color independently, which I think makes sense.
This results in MQTT commands like:

```
16/01/2025 01:27:48 awtrix/office/moodlight {"color":[212,178,255]}      # me playing with color picker
16/01/2025 01:27:48 awtrix/office/moodlight {"brightness":30}                # me playing with brightness slider
```

The issue is that when the payload only includes color (not brightness), Awtrix uses a default brightness, instead of preserving the previously set moodlight brightness.

Also, if the clock is not in moodlight mode, and the tweak the brightness, then the brightness of the device really changes, without entering moodlight mode.  But after setting a moodlight color, changing just the brightness has no effect.  There is already a normal setting to set the awtrix brightness, so I'm thinking that just writing brightness to the moodlight topic should engage moodlight mode, using the last color used.  And changing just brightness should work after moodlight mode is enabled.

In summuary, I think changing just the color should not affect brightness, and vice versa.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: v0.98

## To Reproduce

Create light in Home Assistant, play with it.

## Expected behavior

See above.
